<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="5.051" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2025-03-25T11:28:57" tests="0" file="e2e-testing/cypress/e2e/notes.cy.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Notes Management E2E Tests" timestamp="2025-03-25T11:28:57" tests="3" time="5.018" failures="1">
    <testcase name="Notes Management E2E Tests &quot;before each&quot; hook for &quot;should support complete notes workflow&quot;" time="1.648" classname="&quot;before each&quot; hook for &quot;should support complete notes workflow&quot;">
      <failure message="The following error originated from your test code, not from Cypress.

  &gt; Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  &gt; `cy.get()`

The cy command you invoked inside the promise was:

  &gt; `cy.log()`

Because Cypress commands are already promise-like, you don&apos;t need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

https://on.cypress.io/returning-promise-and-commands-in-another-command

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Notes Management E2E Tests`" type="CypressError"><![CDATA[CypressError: The following error originated from your test code, not from Cypress.

  > Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > `cy.get()`

The cy command you invoked inside the promise was:

  > `cy.log()`

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

https://on.cypress.io/returning-promise-and-commands-in-another-command

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Notes Management E2E Tests`
    at cy.<computed> [as log] (http://localhost:3000/__cypress/runner/cypress_runner.js:138922:64)
    at $Cy.eval (webpack:///./cypress/e2e/notes.cy.ts:74:0)
    at listener (http://localhost:3000/__cypress/runner/cypress_runner.js:140914:19)
    at arrayMap (http://localhost:3000/__cypress/runner/cypress_runner.js:18631:23)
    at map (http://localhost:3000/__cypress/runner/cypress_runner.js:27600:14)
    at $Cy.emitMap (http://localhost:3000/__cypress/runner/cypress_runner.js:140916:14)
    at parent.<computed> [as emitMap] (http://localhost:3000/__cypress/runner/cypress_runner.js:140879:32)
    at $Cypress.action (http://localhost:3000/__cypress/runner/cypress_runner.js:41667:21)
    at $Cy.onUncaughtException (http://localhost:3000/__cypress/runner/cypress_runner.js:139049:38)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:139225:28)
From Your Spec Code:
    at Object.visitNotes (webpack:///./cypress/e2e/notes.cy.ts:22:63)
    at Context.eval (webpack:///./cypress/e2e/notes.cy.ts:71:0)
From Your Spec Code:
    at Object.visitNotes (webpack:///./cypress/e2e/notes.cy.ts:22:63)
    at Context.eval (webpack:///./cypress/e2e/notes.cy.ts:71:0)]]></failure>
    </testcase>
  </testsuite>
</testsuites>