<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="63.728" tests="4" failures="1">
  <testsuite name="Root Suite" timestamp="2025-03-25T12:22:19" tests="0" file="e2e-testing/cypress/e2e/notes.cy.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Notes Management E2E Tests" timestamp="2025-03-25T12:22:19" tests="4" time="63.686" failures="1">
    <testcase name="Notes Management E2E Tests &quot;before each&quot; hook for &quot;should support complete notes workflow&quot;" time="21.190" classname="&quot;before each&quot; hook for &quot;should support complete notes workflow&quot;">
      <failure message="Timed out retrying after 20000ms: `cy.wait()` timed out waiting `20000ms` for the 1st request to the route: `getNotes`. No request ever occurred.

https://on.cypress.io/wait

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Notes Management E2E Tests`" type="CypressError"><![CDATA[CypressError: Timed out retrying after 20000ms: `cy.wait()` timed out waiting `20000ms` for the 1st request to the route: `getNotes`. No request ever occurred.

https://on.cypress.io/wait

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Notes Management E2E Tests`
    at cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:75176:18)
    at Object.errByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:75230:10)
    at checkForXhr (http://localhost:3000/__cypress/runner/cypress_runner.js:136105:84)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:136131:28)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1777:23)
    at Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:4285:29)
    at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:144517:68)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:144458:14)
    at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1777:23)
    at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:1489:31)
    at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:1546:18)
    at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:1591:10)
    at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:1671:18)
    at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:1615:18)
    at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:5420:46)]]></failure>
    </testcase>
  </testsuite>
</testsuites>